### ISSUE TITLE
Initial requirements

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-runner#1]
- [ ] Create dockerfile that will load a given tar file as runnable client code.

The colisee-runner should:

- [ ] Spin up cerveau from docker https://hub.docker.com/r/siggame/cerveau/
- [x] Pull the oldest, status=scheduled, game off the database
- [x] Mark game as status=playing
- [x] Determine which players are playing this game
- [ ] Pull the respective players' Tarred code from the GitLab API
- [ ] Build runnable Docker instances from client code
- [x] Run dockerized clients on the same session of the game server.
- [x] Wait for both to exit
- [x] Retrieve game status from game server
- [ ] Retrieve game log from game server
- [x] Update database with winner
- [x] Update database with gamelog
- [x] Mark game as finished

NOTE: Marking of the game as playing should be combined with pulling the game as a single atomic operation

**Comment by russleyshaw** [comment]
Note: the original issue is pretty old. New requirements should be made.

**Comment by user404d** [comment]
I'm changing some of the requirements above.

Removing:
~~- [ ] Spin up cerveau from docker https://hub.docker.com/r/siggame/cerveau/~~

~~- [ ]  Pull the respective players' Tarred code from the GitLab API~~

~~- [ ]  Build runnable Docker instances from client code~~

Adding:

- [x] Pull submission images from registry

- [x] Run pulled submission image

**Comment by user404d** [comment]
I may bring back the first one, but I think it should be handled by our deployment configuration.

**Comment by user404d** [comment]
closing in favor of siggame/colisee#11
